[package]
name = "eddie"
version = "0.1.0"
authors = ["Andrea Tupini <tupini07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
tui = "0.11.0"
termion = "1.5.5"
dirs = "3.0.1"
walkdir = "2.3.1"

[dev-dependencies]
rand = "0.7.3"
pretty_assertions = "0.6.1"